trigger:
- main

pool:
  name: mycomputeragent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      choco install nginx -y
      echo "<h1>Hello World</h1>" | Out-File -FilePath 'C:\Program Files\nginx\html\index.html' -Encoding utf8
  displayName: 'Install Nginx and Deploy Hello World'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Start-Service nginx
  displayName: 'Restart Nginx Service'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -UseBasicParsing http://localhost
  displayName: 'Test Nginx Deployment'
