trigger:
- main

pool:
  name: mycomputeragent

steps:
- script: |
    choco install nginx -y
    mkdir sim

- script: |
    Invoke-WebRequest http://localhost:80
  displayName: 'Test Nginx Deployment'
