trigger:
- master

pool:
  name: newagent

steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'update.sh'
  displayName: 'Updating Ubuntu Server'

- script: |
    sudo apt-get update
    sudo apt-get install nginx -y
    echo "<h1>Hello World deployed using Azure Pipeline</h1>" | sudo tee /var/www/html/index.html
  displayName: 'Install Nginx and Deploy Hello World'

- task: ShellScript@2
  inputs:
    scriptPath: 'restartnginx.sh'
  displayName: 'Restart Nginx Service'


