trigger:
- main

pool:
  name: mycomputeragent

steps:
- script: |
    choco install nginx -y
    echo "<h1>Hello World</h1>" | Out-File -FilePath 'C:\Program Files (x86)\nginx\html\index.html' -Encoding utf8
  displayName: 'Install Nginx and Deploy Hello World'

- script: |
    sc.exe stop nginx
    sc.exe start nginx
  displayName: 'Restart Nginx Service'

- script: |
    Invoke-WebRequest http://localhost:80
  displayName: 'Test Nginx Deployment'
