trigger:
- master

resources:
- repo: self

pool: newagent

stages:
- task: Docker@2
  inputs:
    containerRegistry: 'myconnection'
    repository: 'meriregistryhai'
    command: 'build'
    Dockerfile: 'Dockerfile'
