trigger:
- main

pool:
  name: mycomputeragent

steps:
- script: |
    sudo apt-get update -y
    sudo apt-get install nginx -y
    sudo systemctl start nginx
    echo "<h1>Hello World</h1>" | sudo tee /var/www/html/index.html
  displayName: 'Install Nginx and Deploy Hello World'

- script: |
    sudo systemctl restart nginx
  displayName: 'Restart Nginx Service'

- script: |
    curl http://20.244.35.154
  displayName: 'Test Nginx Deployment'
