trigger:
- master

pool:
  name: newagent

steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'update.sh'
  displayName: 'Updating Ubuntu Server'

- script: |
    sudo apt-get update -y
    sudo apt-get install nginx -y
    echo "<h1>Hello World deployed using Azure Pipeline</h1>" | sudo tee /var/www/html/index.html
    sudo apt-get install docker.io -y
    sudo systemctl start docker
    sudo systemctl enable docker
  displayName: 'Install Nginx and other softwares'

- task: ShellScript@2
  inputs:
    scriptPath: 'restartnginx.sh'
  displayName: 'Restart Nginx Service'

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    repository: 'meriregistryhai.azurecr.io/myimage'
    tags: 'latest'

- task: Docker@2
  displayName: 'Run Docker container'
  inputs:
    command: 'run'
    repository: 'meriregistryhai.azurecr.io/myimage'
    containerName: 'mycontainer'
    detach: true
    ports: '80:80'
