trigger:
- master

pool:
  name: newagent

variables:
- name: mypassword
  value: $(mypassword)
  allowOverride: true
  secret: true

steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'update.sh'
  displayName: 'Updating Ubuntu Server'

- script: |
    sudo apt-get update -y
    sudo apt-get install nginx -y
    echo "<h1>Hello World deployed using Azure Pipeline</h1>" | sudo tee /var/www/html/index.html
    sudo apt-get install docker.io -y
    sudo systemctl start docker
    sudo systemctl enable docker
  displayName: 'Install Nginx and other softwares'

- task: ShellScript@2
  inputs:
    scriptPath: 'restartnginx.sh'
  displayName: 'Restart Nginx Service'

- task: Docker@2
  inputs:
    containerRegistry: 'meriregistryhai'
    repository: 'meriregistryhai'
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: 'latest'
    arguments: '--build-arg PASSWORD=$(mypassword)'

- task: Docker@2
  inputs:
    containerRegistry: 'meriregistryhai'
    repository: 'meriregistryhai'
    command: 'push'
    tags: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'meriregistryhai'
    command: 'login'
    arguments: '-u $(containerRegistry) -p $(mypassword)'

- script: |
    docker run -d -p 80:80 meriregistryhai:latest
  displayName: 'Run Container'
