trigger:
- master

pool: newagent

resources:
- repo: self

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'myconnection'
    repository: 'meriregistryhai'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
