trigger:
- master

resources:
- repo: self

pool: newagent

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'myconnection'
        repository: 'meriregistryhai'
        command: 'build'
        Dockerfile: 'Dockerfile'
