trigger:
- master

pool:
  name: newagent

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: meriregistryhai.azurecr.io/imagename
    command: build
    Dockerfile: Dockerfile
    buildContext: $(System.DefaultWorkingDirectory)
  containerRegistry: meriregistryhai
